
## Name: Rishon Dabre
## Rollno: 51
### Subject: DL
### Experiment No: 1

In [2]:
#!pip install torch torchvision torchaudio -q

In [3]:
import torch

print("========== PART A : VERIFICATION ==========")

# PyTorch Version
print("PyTorch Version:", torch.__version__)

# GPU Check
gpu_available = torch.cuda.is_available()
print("GPU Available:", gpu_available)

if gpu_available:
    print("GPU Name:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")

========== PART A : VERIFICATION ==========
PyTorch Version: 2.11.0+cpu
GPU Available: False
Running on CPU


In [4]:
print("========== PART B : TENSOR CREATION ==========")

scalar = torch.tensor(10)

vector = torch.tensor([1, 2, 3, 4, 5])

matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("\nScalar Tensor:")
print(scalar)

print("\nVector Tensor:")
print(vector)

print("\nMatrix Tensor:")
print(matrix)

print("\n3-D Tensor:")
print(tensor_3d)

print("\n----- Dimensions -----")
print("Scalar Dimension:", scalar.ndim)
print("Vector Dimension:", vector.ndim)
print("Matrix Dimension:", matrix.ndim)
print("3-D Tensor Dimension:", tensor_3d.ndim)

print("\n----- Data Types -----")
print("Scalar:", scalar.dtype)
print("Vector:", vector.dtype)
print("Matrix:", matrix.dtype)
print("3-D Tensor:", tensor_3d.dtype)

print("\n----- Shapes -----")
print("Scalar Shape:", scalar.shape)
print("Vector Shape:", vector.shape)
print("Matrix Shape:", matrix.shape)
print("3-D Tensor Shape:", tensor_3d.shape)

========== PART B : TENSOR CREATION ==========

Scalar Tensor:
tensor(10)

Vector Tensor:
tensor([1, 2, 3, 4, 5])

Matrix Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

3-D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

----- Dimensions -----
Scalar Dimension: 0
Vector Dimension: 1
Matrix Dimension: 2
3-D Tensor Dimension: 3

----- Data Types -----
Scalar: torch.int64
Vector: torch.int64
Matrix: torch.int64
3-D Tensor: torch.int64

----- Shapes -----
Scalar Shape: torch.Size([])
Vector Shape: torch.Size([5])
Matrix Shape: torch.Size([2, 3])
3-D Tensor Shape: torch.Size([2, 2, 2])


In [5]:
print("========== PART C : TENSOR OPERATIONS ==========")

A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)

print("\nMatrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition (A + B):")
print(A + B)

print("\nSubtraction (A - B):")
print(A - B)

print("\nElement-wise Multiplication (A * B):")
print(A * B)

print("\nMatrix Multiplication (A @ B):")
print(torch.matmul(A, B))

# Reshape
print("\nReshape A to (4,1):")
print(A.reshape(4, 1))

# Transpose
print("\nTranspose of A:")
print(A.T)

========== PART C : TENSOR OPERATIONS ==========

Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

Addition (A + B):
tensor([[ 6.,  8.],
        [10., 12.]])

Subtraction (A - B):
tensor([[-4., -4.],
        [-4., -4.]])

Element-wise Multiplication (A * B):
tensor([[ 5., 12.],
        [21., 32.]])

Matrix Multiplication (A @ B):
tensor([[19., 22.],
        [43., 50.]])

Reshape A to (4,1):
tensor([[1.],
        [2.],
        [3.],
        [4.]])

Transpose of A:
tensor([[1., 3.],
        [2., 4.]])


In [8]:
print("========== PART D : AUTOMATIC DIFFERENTIATION ==========")

x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3*x + 1

y.backward()

print("x =", x.item())
print("y =", y.item())
print("dy/dx =", x.grad.item())

========== PART D : AUTOMATIC DIFFERENTIATION ==========
x = 2.0
y = 11.0
dy/dx = 7.0
